### PR TITLE
Ajc 39/json parser exception

### LINKED ISSUE #39: Fix JsonParser error on extract Exception.
When error response is not from AL API the exception extract method throws a jsonParser exception. This can occur if there is an nginx error instead.

### PR DESCRIPTION
**Pull request by cpmccle**
closes #39

### CODE REVIEW

File: src/main/java/ca/gc/cyber/ops/assemblyline/java/client/clients/AssemblylineClient.java [hunk 1]
```diff
@@ -413,12 +414,17 @@ protected void setSession(ClientResponse clientResponse) {
         return Mono.just(rc);
     }
 
-    private String extractApiErrorMessage(WebClientResponseException exception) throws JsonProcessingException {
+    private String extractApiErrorMessage(WebClientResponseException exception) {
+        var exceptionMessage = exception.getResponseBodyAsString();
```
Comment (cccs-mk) [inline src/main/java/ca/gc/cyber/ops/assemblyline/java/client/clients/AssemblylineClient.java:418]: Can this be put directly in the `return` statement so that it only gets executed when it's needed?

**Review by cccs-mk — APPROVED** [review]
